plugins:
  media_indexer_enabled:
    default: true
    client: false
  media_indexer_root_path:
    default: "/mnt/media/public"
    client: false
  media_indexer_extensions:
    default: "jpg|jpeg|png|gif|webp|mp4|webm|mkv|mov"
    client: false
  media_indexer_public_prefix:
    default: "/media"
    client: true