plugins:
  media_indexer_enabled:
    default: true
    client: false
  media_indexer_root_path:
    default: "/mnt/media/public"
    client: false
  media_indexer_extensions:
    default: "mp4|webm|jpg|jpeg|png|webp"
    client: false